export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

export const GET_FAVORITES_REQUEST = 'GET_FAVORITES_REQUEST';
export const GET_FAVORITES_SUCCESS = 'GET_FAVORITES_SUCCESS';
export const GET_FAVORITES_ERROR = 'GET_FAVORITES_ERROR';

export const SET_PRODUCTS = 'SET_PRODUCTS';

export const GET_PRIVATE_PRODUCTS_REQUEST = 'GET_PRIVATE_PRODUCTS_REQUEST';
export const GET_PRIVATE_PRODUCTS_SUCCESS = 'GET_PRIVATE_PRODUCTS_SUCCESS';
export const GET_PRIVATE_PRODUCTS_ERROR = 'GET_PRIVATE_PRODUCTS_ERROR';

export const SET_PRIVATE_PRODUCTS = 'SET_PRIVATE_PRODUCTS';